name: gs-proxy
serviceType: "managed"
replicaCount: 1

image:
  repository: quay.io/giantswarm/gs-proxy
  tag: "0.0.0-67b552750b5b469040624af55894527dcb4d6321"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "proxy.hackathon-dx.gaws.gigantic.io"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    giantswarm.io/external-dns: managed

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
