name: gs-proxy
serviceType: "managed"
replicaCount: 1

image:
  repository: quay.io/giantswarm/gs-proxy
  tag: "0.0.0-378839f763421eb458a3594ab5a24d23b00cd2c2"
  pullPolicy: IfNotPresent

# Authentication configuration
auth:
  enabled: true
  createSecret: true

  secret:
    name: "gs-proxy-auth"
    usernameKey: "username"
    passwordKey: "password"

  credentials:
    username: "admin"
    password: "changeme"

service:
  type: LoadBalancer
  port: 8000
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "proxy.hackathon-dx.gaws.gigantic.io"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    giantswarm.io/external-dns: managed

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
