apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-proxy
  namespace: default
  labels:
    app: gs-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-proxy
  template:
    metadata:
      labels:
        app: gs-proxy
    spec:
      containers:
      - name: gs-proxy
        image: quay.io/giantswarm/gs-proxy:0.0.0-67b552750b5b469040624af55894527dcb4d6321
        ports:
        - containerPort: 8000
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
