apiVersion: v1
kind: Service
metadata:
  name: gs-proxy
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "proxy.hackathon-dx.gaws.gigantic.io"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    giantswarm.io/external-dns: managed
  labels:
    app: gs-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: gs-proxy
